//ADMIN Constants

export const ADMIN_FILE_SUCCESS = "ADMIN_FILE_SUCCESS";
export const ADMIN_FILE_REQUEST = "ADMIN_FILE_REQUEST";
export const ADMIN_FILE_FAILURE = "ADMIN_FILE_FAILURE";

// get  All user  CONSTANTS

export const LIST_USER_REQUEST = "LIST_USER_REQUEST";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const LIST_USER_FAILURE = "LIST_USER_FAILURE";
// GET  Parameter CONSTANTS

export const ADMIN_PARAMETER_REQUEST = "ADMIN_PARAMETER_REQUEST";
export const ADMIN_PARAMETER_SUCCESS = "ADMIN_PARAMETER_SUCCESS";
export const ADMIN_PARAMETER_FAILURE = "ADMIN_PARAMETER_FAILURE";

//  Admin Update For Parameter
export const UPDATE_ADMIN_PARAMETER_REQUEST = "UPDATE_ADMIN_PARAMETER_REQUEST";
export const UPDATE_ADMIN_PARAMETER_SUCCESS = "UPDATE_ADMIN_PARAMETER_SUCCESS";
export const UPDATE_ADMIN_PARAMETER_FAILURE = "UPDATE_ADMIN_PARAMETER_FAILURE";


// GET  Subcriber  CONSTANTS

export const ADMIN_SUBCRIBER_REQUEST = "ADMIN_SUBCRIBER_REQUEST";
export const ADMIN_SUBCRIBER_SUCCESS = "ADMIN_SUBCRIBER_SUCCESS";
export const ADMIN_SUBCRIBER_FAILURE = "ADMIN_SUBCRIBER_FAILURE";

//  Admin Update For Subcriber
export const UPDATE_ADMIN_SUBCRIBER_REQUEST = "UPDATE_ADMIN_SUBCRIBER_REQUEST";
export const UPDATE_ADMIN_SUBCRIBER_SUCCESS = "UPDATE_ADMIN_SUBCRIBER_SUCCESS";
export const UPDATE_ADMIN_SUBCRIBER_FAILURE = "UPDATE_ADMIN_SUBCRIBER_FAILURE";

//Get one user Profiel
export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAILURE = "USER_PROFILE_FAILURE";