//Login Constants

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILURE = "USER_REGISTER_FAILURE";



export const USER_FORGETPASS_REQUEST = "USER_FORGETPASS_REQUEST";
export const USER_FORGETPASS_SUCCESS = "USER_FORGETPASS_SUCCESS";
export const USER_FORGETPASS_FAILURE = "USER_FORGETPASS_FAILURE";

//Logout
export const USER_LOGOUT = "USER_LOGOUT";
